# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FireScarMapperDialog
                                 A QGIS plugin
 Generate georeferenced fire scar rasters using a pre-trained U-Net model and analyze the impact of fire events by comparing pre- and post-fire satellite images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-25
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Fire 2A
        email                : N/A
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtWidgets import QDialog, QVBoxLayout, QTabWidget
from .tiff_generator_tab import TiffGeneratorTab
from .layer_selection_tab import LayerSelectionDialog


class FireScarMapperDialog(QDialog):
    def __init__(self, iface, parent=None):
        super().__init__(parent)
        self.iface = iface
        self.setWindowTitle("Fire Scar Mapper")

        # Layout principal
        layout = QVBoxLayout()

        # Crear el QTabWidget con las pestañas
        self.tabs = QTabWidget()
        self.tabs.addTab(TiffGeneratorTab(self.iface, self), "Generate Images")
        self.tabs.addTab(LayerSelectionDialog(self.iface, self), "Generate Fire Scar")

        # Agregar los tabs al layout
        layout.addWidget(self.tabs)
        self.setLayout(layout)

