# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FireScarMapperDialog
                                 A QGIS plugin
 Generate georeferenced fire scar rasters using a pre-trained U-Net model and analyze the impact of fire events by comparing pre- and post-fire satellite images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-25
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Fire 2A
        email                : N/A
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtWidgets import QDockWidget, QTabWidget, QVBoxLayout, QWidget
from .tiff_generator_tab import TiffGeneratorTab
from .layer_selection_tab import LayerSelectionDialog


class FireScarMapperDialog(QDockWidget):
    def __init__(self, iface, parent=None):
        super().__init__(parent)
        self.iface = iface
        self.setWindowTitle("Fire Scar Mapper")

        # Layout principal
        main_widget = QWidget()
        layout = QVBoxLayout()

        # Crear el QTabWidget con las pestañas
        self.tabs = QTabWidget()
        self.tabs.currentChanged.connect(self.on_tab_changed)

        self.tabs.addTab(TiffGeneratorTab(self.iface, self), "Generate Images")
        self.layer_tab = LayerSelectionDialog(self.iface, self)
        self.tabs.addTab(self.layer_tab, "Generate Fire Scar")


        # Agregar los tabs al layout
        layout.addWidget(self.tabs)
        main_widget.setLayout(layout)

        # Establecer el widget principal del Dock
        self.setWidget(main_widget)
    
    def on_tab_changed(self, index):
        # Si es la pestaña 1 (segunda), actualiza los ComboBox
        if index == 1:
            self.layer_tab.populate_layer_combos()


