# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PreAndPostFireTiffGeneratorDockWidget
                                 A QGIS plugin
 This Plugin creates a Pre and Post Fire Tiff file depending on the client input
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Diego - Fire2A
        email                : diego@fire2a.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import  QDate, Qt
from qgis.core import QgsProject, QgsRasterLayer
from qgis.gui import QgsMapToolEmitPoint
from qgis.PyQt.QtWidgets import QWidget, QMessageBox

import ee
import requests

from osgeo import gdal

def set_band_names(tif_path, band_names):
    ds = gdal.Open(tif_path, gdal.GA_Update)
    if ds:
        for i, name in enumerate(band_names, start=1):
            ds.GetRasterBand(i).SetDescription(name)
        ds.FlushCache()
        ds = None
        print(f"✅ Band names assigned to {tif_path}")
    else:
        print(f"⚠️ {tif_path} can't be opened to edit the bands.")


def ensure_results_folder():
    plugin_dir = os.path.dirname(__file__)
    results_dir = os.path.join(plugin_dir, "results", "images")
    os.makedirs(results_dir, exist_ok=True)
    return results_dir

def get_unique_filepath(base_path):
    """
    If file exists, add numeric suffix _2, _3, etc., until finding one available.
    """
    if not os.path.exists(base_path):
        return base_path

    directory, filename = os.path.split(base_path)
    name, ext = os.path.splitext(filename)

    i = 2
    while True:
        new_filename = f"{name}_{i}{ext}"
        new_path = os.path.join(directory, new_filename)
        if not os.path.exists(new_path):
            return new_path
        i += 1

def format_fire_id(start_date, lat, lon):
    """
    Build a compact, unambiguous fire identifier string.
    Examples:
      -38.50, -71.20  ->  2018-01-28_S3850_W7120
       38.50,  71.20  ->  2018-01-28_N3850_E7120
    """
    lat_code = f"{'S' if lat < 0 else 'N'}{int(abs(lat) * 100):04d}"
    lon_code = f"{'W' if lon < 0 else 'E'}{int(abs(lon) * 100):04d}"
    date_ddmmyyyy = f"{start_date[8:10]}-{start_date[5:7]}-{start_date[0:4]}"
    return f"{date_ddmmyyyy}_{lat_code}_{lon_code}"


class FireIgnitionTool(QgsMapToolEmitPoint):
    def __init__(self, iface, callback):
        super().__init__(iface.mapCanvas())
        self.iface = iface
        self.canvas = iface.mapCanvas()
        self.callback = callback
        self.setCursor(Qt.CrossCursor)
        print("🔥 FireIgnitionTool Activated. Click on the map to select an ignition point.")

    def canvasReleaseEvent(self, event):
        point = self.toMapCoordinates(event.pos())
        if point:
            print(f"📍 Ignition Point Selected: {point.x()}, {point.y()}")
            self.callback(point)
            self.canvas.unsetMapTool(self)
            print("🔄 Tool deactivated after the selection.")
        else:
            print("⚠️ Ignition Point couldn't be obtained.")

class TiffGeneratorTab(QWidget):
    #closingPlugin = pyqtSignal()

    def __init__(self, iface, parent=None):
        super().__init__(parent)
        self.iface = iface

        # UI Setup
        self.setWindowTitle("Wildfire TIFF Generator")
        layout = QtWidgets.QVBoxLayout()

        # Punto de ignición
        self.label_point = QtWidgets.QLabel("Ignition Point: Not Selected")
        self.btn_select_point = QtWidgets.QPushButton("📍 Select an Ignition Point on the Map")
        self.btn_select_point.clicked.connect(self.select_point)

        # Fechas
        self.label_start_date = QtWidgets.QLabel("Start Date (DD-MM-YYYY):")
        self.start_date = QtWidgets.QDateEdit()
        self.start_date.setCalendarPopup(True)
        self.start_date.setDate(QDate.currentDate())

        self.label_end_date = QtWidgets.QLabel("End Date (DD-MM-YYYY):")
        self.end_date = QtWidgets.QDateEdit()
        self.end_date.setCalendarPopup(True)
        self.end_date.setDate(QDate.currentDate())

        # Área o longitud del recuadro
        self.label_area = QtWidgets.QLabel("Estimated Area of the Wildfire (ha):")
        self.area_input = QtWidgets.QDoubleSpinBox()
        self.area_input.setRange(0, 100000)
        self.area_input.setSuffix(" ha")
        self.area_input.setToolTip(
            "Estimated size of the fire in hectares.\n"
            "Used to calculate the image extent around the ignition point.\n"
            "Values above 1,275 ha will be automatically adjusted to avoid\n"
            "exceeding Google Earth Engine's download limits."
        )
        
        # Checkbox para búsqueda extendida
        self.extended_search_checkbox = QtWidgets.QCheckBox(
            "Include images from 1 year before fire (350–470 days prior)"
        )
        self.extended_search_checkbox.setToolTip(
            "When checked, also searches for pre-fire images between\n"
            "350 and 470 days before the fire start date.\n"
            "Use this if the default 180-day window does not provide\n"
            "enough cloud-free images."
        )
        
        
        # Botón para generar el TIFF
        self.btn_generate = QtWidgets.QPushButton("🛰️ Generate Pre and Post Fire Tiff Images")
        self.btn_generate.clicked.connect(self.generate_tiff)

        # Agregar widgets al layout
        layout.addWidget(self.label_point)
        layout.addWidget(self.btn_select_point)
        layout.addWidget(self.label_start_date)
        layout.addWidget(self.start_date)
        layout.addWidget(self.label_end_date)
        layout.addWidget(self.end_date)
        layout.addWidget(self.label_area)
        layout.addWidget(self.area_input)
        layout.addWidget(self.extended_search_checkbox)
        layout.addWidget(self.btn_generate)
        layout.addStretch()

        self.setLayout(layout)

        self.ignition_point = None
        self.ee_initialize()

    def ee_initialize(self):
        try:
            ee.Initialize()
            self.gee_initialized = True
        except Exception as e:
            self.gee_initialized = False
            print(f"Error at initializing Google Earth Engine: {e}")

    def select_point(self):
        print("🛠 Activating Ignition Point Selection Tool...")
        self.tool = FireIgnitionTool(self.iface, self.set_point)
        self.iface.mapCanvas().setMapTool(self.tool)
        self.iface.mapCanvas().refresh()

    def set_point(self, point):
        if point:
            self.ignition_point = point
            self.label_point.setText(f"Ignition Point: {point.x()}, {point.y()}")
            print(f"✅ Ignition Point Confirmed: {point.x()}, {point.y()}")
        else:
            print("⚠️ Error: Couldn't capture a valid point.")

    def generate_tiff(self):
        if not self.gee_initialized:
            QMessageBox.critical(
                self,
                "Google Earth Engine Error",
                "Google Earth Engine is not initialized.\n\n"
                "Please make sure you have:\n"
                "1. Installed the GEE plugin in QGIS\n"
                "2. Linked your GEE account\n"
                "3. Set a valid GEE project ID\n\n"
                "Then restart QGIS and try again."
            )
            return

        if not self.ignition_point:
            QMessageBox.warning(self, "Missing Input", "Please select an ignition point on the map first.")
            self.label_point.setText("Select an Ignition Point first")
            return

        start_date = self.start_date.date()
        end_date = self.end_date.date()

        if end_date < start_date:
            QMessageBox.warning(
                self,
                "Invalid Dates",
                "The end date cannot be earlier than the start date."
            )
            return

        if self.area_input.value() < 1:
            QMessageBox.warning(
                self,
                "Invalid Area",
                "The estimated area must be at least 1 hectare.\n"
                "A value of 0 would generate a buffer too small to capture the fire scar."
            )
            return
        
        area_value = self.area_input.value()
        if area_value > 1275:
            area_value = 1275
            QMessageBox.information(
                self,
                "Area Adjusted",
                "The entered value exceeds the maximum input accepted by the buffer calculation (1,275 ha).\n\n"
                "The value has been automatically adjusted to 1,275 ha. The generated image will still\n"
                "cover an area larger than 1,275 hectares due to the buffer amplification factor.\n\n"
                "If the fire scar is not fully captured, try regenerating the images with\n"
                "a different ignition point closer to the center of the scar."
            )

        start_date_str = start_date.toString("yyyy-MM-dd")
        end_date_str = end_date.toString("yyyy-MM-dd")
        print("🚀 Iniciating Pre and Post-Fire Image generation...")

        lat = self.ignition_point.y()
        lon = self.ignition_point.x()
        self.get_fire_images(start_date_str, end_date_str, area_value, lat, lon)

    def applyScaleFactors(self, image):
        """
        Applies scale factors to Landsat Collection 2 images.

        Parameters:
        image (ee.Image): Input Landsat image.

        Returns:
        ee.Image: Scaled image with reflectance corrections applied.
        """
        opticalBands = image.select('SR_B.*').multiply(0.0000275).add(-0.2)

        hasST_B10 = image.bandNames().contains('ST_B10')
        hasST_B6 = image.bandNames().contains('ST_B6')

        ST_B10 = ee.Algorithms.If(hasST_B10, image.select('ST_B10'), ee.Image(0).rename('ST_B10'))
        ST_B6 = ee.Algorithms.If(hasST_B6, image.select('ST_B6'), ee.Image(0).rename('ST_B6'))

        return image.addBands(opticalBands, overwrite=True).addBands(ee.Image(ST_B10), overwrite=True).addBands(ee.Image(ST_B6), overwrite=True)

    def maskClouds(self, image):
        """
        Masks clouds, cloud shadows, snow, and saturated pixels in Landsat images using the `QA_PIXEL` band.

        Parameters:
        image (ee.Image): The input Landsat image.

        Returns:
        ee.Image: The image with cloud and saturation pixels masked.
        """
        qamask = image.select('QA_PIXEL').bitwiseAnd(int('11111', 2)).eq(0)
        saturationmask = image.select('QA_RADSAT').eq(0)
        return image.updateMask(qamask).updateMask(saturationmask)


    def harmonizeBands(self, image):
        """
        Harmonizes band selection by removing `SR_QA_AEROSOL` if present.

        Parameters:
        image (ee.Image): The input Landsat image.

        Returns:
        ee.Image: The image with consistent band names across sensors.
        """
        bands = image.bandNames()
        filtered = ee.Algorithms.If(
            bands.contains('SR_QA_AEROSOL'),
            image.select(bands.remove('SR_QA_AEROSOL')),
            image
        )
        return ee.Image(filtered)


    def get_INDEX(self, image, sensor):
        """
        Computes NDVI and NBR indices for a Landsat image.

        Parameters:
        image (ee.Image): The input Landsat image.
        sensor (str): The Landsat sensor type ('L5', 'L7', 'L8', 'L9').

        Returns:
        ee.Image: The image with NDVI and NBR bands added.
        """
        bands_dict = {
            'L5': {'NIR': 'SR_B4', 'Red': 'SR_B3', 'SWIR2': 'SR_B7'},
            'L7': {'NIR': 'SR_B4', 'Red': 'SR_B3', 'SWIR2': 'SR_B7'},
            'L8': {'NIR': 'SR_B5', 'Red': 'SR_B4', 'SWIR2': 'SR_B7'},
            'L9': {'NIR': 'SR_B5', 'Red': 'SR_B4', 'SWIR2': 'SR_B7'}
        }
        bands = bands_dict[sensor]

        NDVI = image.expression(
            '(NIR - Red) / (NIR + Red)',
            {'NIR': image.select(bands['NIR']), 'Red': image.select(bands['Red'])}
        ).rename('NDVI')

        NBR = image.expression(
            '((NIR - SWIR2) / (NIR + SWIR2)) * 1000',
            {'NIR': image.select(bands['NIR']), 'SWIR2': image.select(bands['SWIR2'])}
        ).rename('NBR')

        return image.addBands(NDVI).addBands(NBR)


    def renameBands(self, image, sensor):
        """
        Renames bands to maintain consistency across different Landsat sensors.

        Parameters:
        image (ee.Image): The input Landsat image.
        sensor (str): The Landsat sensor type ('L5', 'L7', 'L8', 'L9').

        Returns:
        ee.Image: The image with renamed bands.
        """
        bands_dict = {
            'L5': ['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B7', 'NDVI', 'NBR', 'QA_PIXEL'],
            'L7': ['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B7', 'NDVI', 'NBR', 'QA_PIXEL'],
            'L8': ['SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7', 'NDVI', 'NBR', 'QA_PIXEL'],
            'L9': ['SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7', 'NDVI', 'NBR', 'QA_PIXEL']
        }
        bands = bands_dict[sensor]
        new_bands = ['B', 'G', 'R', 'NIR', 'SWIR1', 'SWIR2', 'NDVI', 'NBR', 'QA_PIXEL']

        available_bands = image.bandNames()
        has_qa_pixel = available_bands.contains('QA_PIXEL')

        return ee.Algorithms.If(
            has_qa_pixel,
            image.select(bands).rename(new_bands),
            image.select(bands[:-1]).rename(new_bands[:-1])
        )

    def adddate(self, image):
        """
        Adds the 'time_start' property to an Earth Engine image.

        Parameters:
        image (ee.Image): The input Earth Engine image.

        Returns:
        ee.Image: The image with the 'time_start' property set.
        """
        return image.set('time_start', image.get('system:time_start'))

    def get_fire_images(self, start_date, end_date, area, lat, lon):
        fire_id = format_fire_id(start_date, lat, lon)
        area = max(area, 0.0001)  
        buffer_size = ee.Number(area).log().multiply(2000).max(3000) 
        buffer_size = ee.Number(163673.1).multiply(ee.Number(1).subtract(ee.Number(-0.001157413).multiply(ee.Number(area).pow(0.5259879)).exp()))  
        buffer_size = buffer_size.multiply(1.5)
        region = ee.Geometry.Point([self.ignition_point.x(), self.ignition_point.y()]).buffer(buffer_size)
            
        pre_end = ee.Date(start_date).advance(-1, 'day')
        pre_start = ee.Date(start_date).advance(-180, 'day')
        post_end = ee.Date(end_date).advance(180, 'day')

        def prepare_collection(collection, sensor, date_start, date_end):
            return collection\
                .filterBounds(region)\
                .filterDate(date_start, date_end)\
                .map(self.applyScaleFactors)\
                .map(self.harmonizeBands)\
                .map(self.maskClouds)\
                .map(lambda img: self.get_INDEX(img, sensor))\
                .map(lambda img: self.renameBands(img, sensor))

        L5_pre = prepare_collection(ee.ImageCollection('LANDSAT/LT05/C02/T1_L2'), 'L5', pre_start, pre_end)
        L7_pre = prepare_collection(ee.ImageCollection('LANDSAT/LE07/C02/T1_L2').filterDate('1999-01-01', '2003-05-31'), 'L7', pre_start, pre_end)
        L8_pre = prepare_collection(ee.ImageCollection('LANDSAT/LC08/C02/T1_L2'), 'L8', pre_start, pre_end)
        L9_pre = prepare_collection(ee.ImageCollection('LANDSAT/LC09/C02/T1_L2'), 'L9', pre_start, pre_end)

        if self.extended_search_checkbox.isChecked():
            ext_start = ee.Date(start_date).advance(-470, 'day')
            ext_end = ee.Date(start_date).advance(-350, 'day')

            L5_pre_ext = prepare_collection(ee.ImageCollection('LANDSAT/LT05/C02/T1_L2'), 'L5', ext_start, ext_end)
            L7_pre_ext = prepare_collection(ee.ImageCollection('LANDSAT/LE07/C02/T1_L2').filterDate('1999-01-01', '2003-05-31'), 'L7', ext_start, ext_end)
            L8_pre_ext = prepare_collection(ee.ImageCollection('LANDSAT/LC08/C02/T1_L2'), 'L8', ext_start, ext_end)
            L9_pre_ext = prepare_collection(ee.ImageCollection('LANDSAT/LC09/C02/T1_L2'), 'L9', ext_start, ext_end)

            L5_pre = L5_pre.merge(L5_pre_ext)
            L7_pre = L7_pre.merge(L7_pre_ext)
            L8_pre = L8_pre.merge(L8_pre_ext)
            L9_pre = L9_pre.merge(L9_pre_ext)

        L5_pos = prepare_collection(ee.ImageCollection('LANDSAT/LT05/C02/T1_L2'), 'L5', ee.Date(end_date), post_end)
        L7_pos = prepare_collection(ee.ImageCollection('LANDSAT/LE07/C02/T1_L2').filterDate('1999-01-01', '2003-05-31'), 'L7', ee.Date(end_date), post_end)
        L8_pos = prepare_collection(ee.ImageCollection('LANDSAT/LC08/C02/T1_L2'), 'L8', ee.Date(end_date), post_end)
        L9_pos = prepare_collection(ee.ImageCollection('LANDSAT/LC09/C02/T1_L2'), 'L9', ee.Date(end_date), post_end)

        mosaicpre = L5_pre.merge(L7_pre).merge(L8_pre).merge(L9_pre)\
            .map(lambda img: self.adddate(img))\
            .sort('system:time_start', True)

        mosaicpos = L5_pos.merge(L7_pos).merge(L8_pos).merge(L9_pos)\
            .map(lambda img: self.adddate(img))\
            .sort('system:time_start', False)
        

        pref = mosaicpre.mosaic().clip(region)
        postf = mosaicpos.mosaic().clip(region)

        print(f"Pre-fire collection size: {L8_pre.size().getInfo()}")
        print(f"Post-fire collection size: {L8_pos.size().getInfo()}")
        print(f"Pre-fire ALL sensors size: {L5_pre.merge(L7_pre).merge(L8_pre).merge(L9_pre).size().getInfo()}")
        print(f"Post-fire ALL sensors size: {L5_pos.merge(L7_pos).merge(L8_pos).merge(L9_pos).size().getInfo()}")
        

        def scale_to_training_range(image):
            """Scale reflectance bands to 0-10000 to match training dataset range."""
            return image.select(['R', 'G', 'B', 'NIR', 'SWIR1', 'SWIR2']).multiply(10000) \
                .rename(['R', 'G', 'B', 'NIR', 'SWIR1', 'SWIR2']) \
                .addBands(image.select(['NDVI', 'NBR']))

        PREImagen = scale_to_training_range(pref).toFloat()
        POSImagen = scale_to_training_range(postf).toFloat()

        results_dir = ensure_results_folder()
        pre_path = get_unique_filepath(os.path.join(results_dir, f"Pre-Fire_{fire_id}.tif"))
        post_path = get_unique_filepath(os.path.join(results_dir, f"Post-Fire_{fire_id}.tif"))

        pre_layer_name  = os.path.splitext(os.path.basename(pre_path))[0]
        post_layer_name = os.path.splitext(os.path.basename(post_path))[0]

        print(f"💾 Downloading Images on temporary files: {pre_path} y {post_path}")

        pre_url = PREImagen.getDownloadUrl({
            'scale': 30,
            'bands': ['R', 'G', 'B', 'NIR', 'SWIR1', 'SWIR2', 'NDVI', 'NBR'],
            'region': region.bounds().getInfo()['coordinates'],
            'crs': 'EPSG:4326',
            'maxPixels': 1e13,
            'format': 'GeoTIFF'
        })

        post_url = POSImagen.getDownloadUrl({
            'scale': 30,
            'bands': ['R', 'G', 'B', 'NIR', 'SWIR1', 'SWIR2', 'NDVI', 'NBR'],
            'region': region.bounds().getInfo()['coordinates'],
            'crs': 'EPSG:4326',
            'maxPixels': 1e13,
            'format': 'GeoTIFF'
        })

        
        def download_image(url, output_path):
            response = requests.get(url, stream=True)
            if response.status_code == 200:
                with open(output_path, 'wb') as file:
                    for chunk in response.iter_content(1024):
                        file.write(chunk)
                print(f"✅ Image Downloaded: {output_path}")
                return True
            else:
                print(f"⚠️ Error status code: {response.status_code}")
                print(f"⚠️ Error response: {response.text[:500]}")
                return False
        
        success_pre = download_image(pre_url, pre_path)
        success_post = download_image(post_url, post_path)

        band_names = ['R', 'G', 'B', 'NIR', 'SWIR1', 'SWIR2', 'NDVI', 'NBR']

        if success_pre and success_post:
            set_band_names(pre_path, band_names)
            set_band_names(post_path, band_names)
            self.add_raster_to_qgis(pre_path, pre_layer_name)
            self.add_raster_to_qgis(post_path, post_layer_name)
            print("✅ Images download complete and added to QGIS.")
        else:
            # Clean up any partial downloads
            if os.path.exists(pre_path):
                os.remove(pre_path)
            if os.path.exists(post_path):
                os.remove(post_path)
            failed = "Pre-Fire" if not success_pre else "Post-Fire"
            raise Exception(
                f"{failed} image download failed.\n\n"
                "This may be caused by:\n"
                "• The estimated area is too large for Google Earth Engine\n"
                "• No satellite imagery available for this date range\n"
                "• Network connection issues\n\n"
                "Try reducing the estimated area or adjusting the dates."
            )

    def add_raster_to_qgis(self, file_path, layer_name):
        """
        Add a TIFF file to the interface of QGIS.

        Parameters:
        file_path (str): TIFF file path.
        layer_name (str): Name of the layer in QGIS.
        """
        if os.path.exists(file_path):
            layer = QgsRasterLayer(file_path, layer_name, "gdal")
            if layer.isValid():
                QgsProject.instance().addMapLayer(layer, False)
                QgsProject.instance().layerTreeRoot().insertLayer(0, layer)
                print(f"🗺️ Layer added to QGIS: {layer_name}")
            else:
                print(f"⚠️ Error: Couldn't load the layer {layer_name}")
        else:
            print(f"⚠️ File doesn't exist: {file_path}")
