name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta[0-9]'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Version bump
      run: |
         VERSION=${GITHUB_REF_NAME#v}
         echo "version is ${VERSION}"
         sed -i -e "s/version=0.0.1/version=${VERSION}/" pan_batido/metadata.txt
         git add firescarmapper/metadata.txt

         lestash=`git stash create`
         git archive --output "fire_scar_mapper_${{ github.ref_name }}.zip" $lestash firescarmapper

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "fire_scar_mapper_${{ github.ref_name }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
